### ISSUE TITLE
Setting Java Path

### ISSUE THREAD

**Issue by AustinEast** [vshaxe/vshaxe-debugadapter#8]
From this line in the Readme: `Additionally, java needs to be in your PATH (to run fdb.jar).`, it sounds like java's path may be hardcoded? Is there a way to configure the java path, to something like `JAVA_HOME`?

**Comment by Gama11** [comment]
Hm... yeah, right now it looks like it's hardcoded to `"java"`, and thus assumes it's available in `PATH`. We should probably check `JAVA_HOME`.

Maybe there should even be a `"haxe-debug.javaPath"` setting where the path can be set explicitly without environment args. Thoughts?

Also, looks like the error handling when Java is not found could use a bit of work...

![](http://i.imgur.com/YuIDEqR.png)

**Comment by Gama11** [comment]
Actually, I'm not sure if debug adapters can contribute settings to `settings.json` (I haven't seen any others do that yet). And a java path setting in launch configs doesn't seem very useful.

**Comment by Gama11** [comment]
Looks like it's possible, but the question is still if it's needed.

**Comment by AustinEast** [comment]
I think for the moment, providing `JAVA_HOME` as an alternative to `PATH` should be good enough. It is sort of the standard for java env variables right? 

Maybe the readme could have more information about setting `JAVA_HOME` or `PATH` for those who aren't familiar with setting env variables, but I don't think it'll need to be included as an outright configurable option.

Thanks for the quick reply!

**Comment by Gama11** [comment]
I've improved the error message a bit too:

![](http://i.imgur.com/vf1IxZR.png)
